### ISSUE TITLE
Device-info config not used on pinephone

### ISSUE THREAD

**Issue by vlladdrakk** [ubports/sensorfw#1]
On the pinephone (kernelUpgrade channel) auto-rotate is not working and the accelerometer data does not show up in the SensorStatus app. Wouter and I were able to track down that sensord was not loading the pinephone.conf file from device-info.

The issue seems to be that in https://github.com/ubports/sensorfw/blob/xenial/sensord/main.cpp on lines 235 and 236 sensord tries to get `sensorfwConfig` from device-info, however it should be `SensorfwConfig` (capital 's') to match the pinephone config in device-info. Whether it is wrong in this code, or the config file in device-info is incorrect I really don't know.

Here are the steps I took to confirm that this is the issue:
1. I added the following line to /etc/deviceinfo/devices/pinephone.yaml
```
  sensorfwConfig: /etc/deviceinfo/sensorfw/pinephone.conf
```
2. Executed `device-info get sensorfwConfig` and confirmed that it returned the correct value.
3. Rebooted the phone

After the reboot auto-rotate worked and accelerometer data showed up in the SensorStatus app.
Please let me know if you need more info.

**Comment by wouter182** [comment]
This can be closed, it is solved.
