### ISSUE TITLE
Android 9: Magnetometer & Compass plugins are missing

### ISSUE THREAD

**Issue by fredldotme** [ubports/sensorfw#7]
Turns out it's a packaging mistake. The plugin is built properly, just not shipped as part of the deb.

Fixed by this PR: https://github.com/ubports/sensorfw/pull/6

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/sensorfw/pull/6

**Comment by luksus42** [comment]
Compass and Magnetometer works now on FP3 (H10).
Tested with SensorStatus and MessWerk Apps.
